//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETBANKING
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBeneficiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBeneficiario()
        {
            this.TblCuentaBeneficiarios = new HashSet<TblCuentaBeneficiario>();
        }
    
        public int BeneficiarioID { get; set; }
        public int UsuarioID { get; set; }
        public int TipoDocumento { get; set; }
        public string Documento { get; set; }
        public string Alias { get; set; }
        public string Correo { get; set; }
        public Nullable<int> BancoID { get; set; }
    
        public virtual TblBanco TblBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCuentaBeneficiario> TblCuentaBeneficiarios { get; set; }
    }
}
