//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE_INTERFACES.wsReferenceTipoTransaccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReferenceTipoTransaccion.IWSTipoTransaccion")]
    public interface IWSTipoTransaccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccionResponse")]
        void CrearTipoTransaccion(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccionResponse")]
        System.Threading.Tasks.Task CrearTipoTransaccionAsync(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccionResponse")]
        void EliminarTipoTransaccion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccionResponse")]
        System.Threading.Tasks.Task EliminarTipoTransaccionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/ModificarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/ModificarTipoTransaccionResponse")]
        void ModificarTipoTransaccion(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/ModificarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/ModificarTipoTransaccionResponse")]
        System.Threading.Tasks.Task ModificarTipoTransaccionAsync(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccionResponse")]
        System.Data.DataTable MostrarTipoTransaccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarTipoTransaccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccionResponse")]
        System.Data.DataTable BuscarTipoTransaccion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarTipoTransaccionAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTipoTransaccionChannel : CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTipoTransaccionClient : System.ServiceModel.ClientBase<CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion>, CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion {
        
        public WSTipoTransaccionClient() {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTipoTransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearTipoTransaccion(string Nombre, string Descripcion) {
            base.Channel.CrearTipoTransaccion(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task CrearTipoTransaccionAsync(string Nombre, string Descripcion) {
            return base.Channel.CrearTipoTransaccionAsync(Nombre, Descripcion);
        }
        
        public void EliminarTipoTransaccion(int id) {
            base.Channel.EliminarTipoTransaccion(id);
        }
        
        public System.Threading.Tasks.Task EliminarTipoTransaccionAsync(int id) {
            return base.Channel.EliminarTipoTransaccionAsync(id);
        }
        
        public void ModificarTipoTransaccion(int id, string Nombre, string Descripcion) {
            base.Channel.ModificarTipoTransaccion(id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task ModificarTipoTransaccionAsync(int id, string Nombre, string Descripcion) {
            return base.Channel.ModificarTipoTransaccionAsync(id, Nombre, Descripcion);
        }
        
        public System.Data.DataTable MostrarTipoTransaccion() {
            return base.Channel.MostrarTipoTransaccion();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarTipoTransaccionAsync() {
            return base.Channel.MostrarTipoTransaccionAsync();
        }
        
        public System.Data.DataTable BuscarTipoTransaccion(int id) {
            return base.Channel.BuscarTipoTransaccion(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarTipoTransaccionAsync(int id) {
            return base.Channel.BuscarTipoTransaccionAsync(id);
        }
    }
}
