//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE_INTERFACES.wsReferenceTipoTransaccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReferenceTipoTransaccion.IWSTipoTransaccion")]
    public interface IWSTipoTransaccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccionResponse")]
        bool CrearTipoTransaccion(string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/CrearTipoTransaccionResponse")]
        System.Threading.Tasks.Task<bool> CrearTipoTransaccionAsync(string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/ActualizarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/ActualizarTipoTransaccionResponse")]
        bool ActualizarTipoTransaccion(int idTipo, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/ActualizarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/ActualizarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarTipoTransaccionAsync(int idTipo, string nombre, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccionResponse")]
        bool EliminarTipoTransaccion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/EliminarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<bool> EliminarTipoTransaccionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccionResponse")]
        System.Data.DataTable MostrarTipoTransaccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/MostrarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarTipoTransaccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccionResponse")]
        System.Data.DataTable BuscarTipoTransaccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccion", ReplyAction="http://tempuri.org/IWSTipoTransaccion/BuscarTipoTransaccionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarTipoTransaccionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTipoTransaccionChannel : CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTipoTransaccionClient : System.ServiceModel.ClientBase<CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion>, CORE_INTERFACES.wsReferenceTipoTransaccion.IWSTipoTransaccion {
        
        public WSTipoTransaccionClient() {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTipoTransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTipoTransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearTipoTransaccion(string nombre, string descripcion) {
            return base.Channel.CrearTipoTransaccion(nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<bool> CrearTipoTransaccionAsync(string nombre, string descripcion) {
            return base.Channel.CrearTipoTransaccionAsync(nombre, descripcion);
        }
        
        public bool ActualizarTipoTransaccion(int idTipo, string nombre, string descripcion) {
            return base.Channel.ActualizarTipoTransaccion(idTipo, nombre, descripcion);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarTipoTransaccionAsync(int idTipo, string nombre, string descripcion) {
            return base.Channel.ActualizarTipoTransaccionAsync(idTipo, nombre, descripcion);
        }
        
        public bool EliminarTipoTransaccion(int id) {
            return base.Channel.EliminarTipoTransaccion(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTipoTransaccionAsync(int id) {
            return base.Channel.EliminarTipoTransaccionAsync(id);
        }
        
        public System.Data.DataTable MostrarTipoTransaccion() {
            return base.Channel.MostrarTipoTransaccion();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarTipoTransaccionAsync() {
            return base.Channel.MostrarTipoTransaccionAsync();
        }
        
        public System.Data.DataTable BuscarTipoTransaccion() {
            return base.Channel.BuscarTipoTransaccion();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarTipoTransaccionAsync() {
            return base.Channel.BuscarTipoTransaccionAsync();
        }
    }
}
