//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoreServices;

namespace CORE_INTERFACES.wsReferenceCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReferenceCliente.IWSCliente")]
    public interface IWSCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/CrearCliente", ReplyAction="http://tempuri.org/IWSCliente/CrearClienteResponse")]
        bool CrearCliente(string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/CrearCliente", ReplyAction="http://tempuri.org/IWSCliente/CrearClienteResponse")]
        System.Threading.Tasks.Task<bool> CrearClienteAsync(string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IWSCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(int id, string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IWSCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(int id, string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/EliminarCliente", ReplyAction="http://tempuri.org/IWSCliente/EliminarClienteResponse")]
        bool EliminarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/EliminarCliente", ReplyAction="http://tempuri.org/IWSCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/MostrarClientes", ReplyAction="http://tempuri.org/IWSCliente/MostrarClientesResponse")]
        System.Collections.Generic.List<Cliente> MostrarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/MostrarClientes", ReplyAction="http://tempuri.org/IWSCliente/MostrarClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente>> MostrarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/BuscarCliente", ReplyAction="http://tempuri.org/IWSCliente/BuscarClienteResponse")]
        System.Collections.Generic.List<Cliente> BuscarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCliente/BuscarCliente", ReplyAction="http://tempuri.org/IWSCliente/BuscarClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente>> BuscarClienteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSClienteChannel : CORE_INTERFACES.wsReferenceCliente.IWSCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClienteClient : System.ServiceModel.ClientBase<CORE_INTERFACES.wsReferenceCliente.IWSCliente>, CORE_INTERFACES.wsReferenceCliente.IWSCliente {
        
        public WSClienteClient() {
        }
        
        public WSClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CrearCliente(string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento) {
            return base.Channel.CrearCliente(nombre, tipoDocumento, documento, correo, telefono, direccion, fechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<bool> CrearClienteAsync(string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento) {
            return base.Channel.CrearClienteAsync(nombre, tipoDocumento, documento, correo, telefono, direccion, fechaNacimiento);
        }
        
        public bool ActualizarCliente(int id, string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento) {
            return base.Channel.ActualizarCliente(id, nombre, tipoDocumento, documento, correo, telefono, direccion, fechaNacimiento);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(int id, string nombre, int tipoDocumento, string documento, string correo, string telefono, string direccion, System.DateTime fechaNacimiento) {
            return base.Channel.ActualizarClienteAsync(id, nombre, tipoDocumento, documento, correo, telefono, direccion, fechaNacimiento);
        }
        
        public bool EliminarCliente(int id) {
            return base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(int id) {
            return base.Channel.EliminarClienteAsync(id);
        }
        
        public System.Collections.Generic.List<Cliente> MostrarClientes() {
            return base.Channel.MostrarClientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente>> MostrarClientesAsync() {
            return base.Channel.MostrarClientesAsync();
        }
        
        public System.Collections.Generic.List<Cliente> BuscarCliente(int id) {
            return base.Channel.BuscarCliente(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Cliente>> BuscarClienteAsync(int id) {
            return base.Channel.BuscarClienteAsync(id);
        }
    }
}
