//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public int id_caja { get; set; }
        public int id_sucursal { get; set; }
        public Nullable<decimal> monto_caja { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
    
        public virtual sucursale sucursale { get; set; }
    }
}
