//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadre
    {
        public int id_cuadres { get; set; }
        public int id_cajero { get; set; }
        public decimal monto_inicial { get; set; }
        public decimal monto_final { get; set; }
        public decimal diferencia_cuadre { get; set; }
        public System.DateTime fecha_cuadre { get; set; }
    
        public virtual cajero cajero { get; set; }
    }
}
