//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo
    {
        public int id_recibo { get; set; }
        public int id_transaccion { get; set; }
        public decimal monto_transaccion { get; set; }
        public System.DateTime fecha_transaccion { get; set; }
    
        public virtual transaccione transaccione { get; set; }
    }
}
