//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sucursale()
        {
            this.cajas = new HashSet<caja>();
            this.cajeros = new HashSet<cajero>();
        }
    
        public int id_sucursal { get; set; }
        public string nombre_sucursal { get; set; }
        public string telefono_sucursal { get; set; }
        public string direccion_sucursal { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caja> cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajero> cajeros { get; set; }
    }
}
