//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAJA
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaccione()
        {
            this.recibos = new HashSet<recibo>();
        }
    
        public int id_transaccion { get; set; }
        public int id_cajero { get; set; }
        public int num_cuenta_origen { get; set; }
        public int num_cuenta_destino { get; set; }
        public int id_moneda { get; set; }
        public int id_tipo_transaccion { get; set; }
        public decimal monto_transaccion { get; set; }
        public System.DateTime fecha_transaccion { get; set; }
        public int id_estado_transaccion { get; set; }
        public int id_prestamo { get; set; }
    
        public virtual cajero cajero { get; set; }
        public virtual estado_transaccion estado_transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibo> recibos { get; set; }
        public virtual tipo_transaccion tipo_transaccion { get; set; }
    }
}
