//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiario()
        {
            this.Cuenta_Beneficiario = new HashSet<Cuenta_Beneficiario>();
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int idBeneficiario { get; set; }
        public int idBanco { get; set; }
        public int TipoDocumento { get; set; }
        public string Documento { get; set; }
        public string Alias { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Beneficiario> Cuenta_Beneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
