//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Beneficiario
    {
        public int idCuenta { get; set; }
        public int idBeneficiario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Beneficiario Beneficiario { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
