//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Cuenta_Beneficiario = new HashSet<Cuenta_Beneficiario>();
            this.Movimiento = new HashSet<Movimiento>();
            this.Prestamo = new HashSet<Prestamo>();
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int idCuenta { get; set; }
        public int idCliente { get; set; }
        public int idTipoCuenta { get; set; }
        public int idBanco { get; set; }
        public string NumeroCuenta { get; set; }
        public bool Estado { get; set; }
        public decimal Balance { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Beneficiario> Cuenta_Beneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
    }
}
