//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Detalle_Prestamo = new HashSet<Detalle_Prestamo>();
        }
    
        public int idPrestamo { get; set; }
        public int idCuenta { get; set; }
        public decimal Tasa { get; set; }
        public decimal MontoOriginal { get; set; }
        public decimal MontoActual { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Prestamo> Detalle_Prestamo { get; set; }
    }
}
