//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int idTransaccion { get; set; }
        public int idTipo { get; set; }
        public int idMoneda { get; set; }
        public int idEstado { get; set; }
        public int CuentaOrigen { get; set; }
        public int CuentaDestino { get; set; }
        public decimal Monto { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Beneficiario Beneficiario { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
