//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoreServices;

namespace CORE_INTERFACES.wsReferenceMovimiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReferenceMovimiento.IWSMovimiento")]
    public interface IWSMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMovimiento/MostrarMovimientoCuenta", ReplyAction="http://tempuri.org/IWSMovimiento/MostrarMovimientoCuentaResponse")]
        System.Collections.Generic.List<Movimiento> MostrarMovimientoCuenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSMovimiento/MostrarMovimientoCuenta", ReplyAction="http://tempuri.org/IWSMovimiento/MostrarMovimientoCuentaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Movimiento>> MostrarMovimientoCuentaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSMovimientoChannel : CORE_INTERFACES.wsReferenceMovimiento.IWSMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMovimientoClient : System.ServiceModel.ClientBase<CORE_INTERFACES.wsReferenceMovimiento.IWSMovimiento>, CORE_INTERFACES.wsReferenceMovimiento.IWSMovimiento {
        
        public WSMovimientoClient() {
        }
        
        public WSMovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Movimiento> MostrarMovimientoCuenta() {
            return base.Channel.MostrarMovimientoCuenta();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Movimiento>> MostrarMovimientoCuentaAsync() {
            return base.Channel.MostrarMovimientoCuentaAsync();
        }
    }
}
