//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE_INTERFACES.wsReferencePerfil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsReferencePerfil.IWSPerfil")]
    public interface IWSPerfil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/CrearPerfil", ReplyAction="http://tempuri.org/IWSPerfil/CrearPerfilResponse")]
        void CrearPerfil(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/CrearPerfil", ReplyAction="http://tempuri.org/IWSPerfil/CrearPerfilResponse")]
        System.Threading.Tasks.Task CrearPerfilAsync(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/EliminarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/EliminarPerfilResponse")]
        void EliminarPerfil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/EliminarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/EliminarPerfilResponse")]
        System.Threading.Tasks.Task EliminarPerfilAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/ModificarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/ModificarPerfilResponse")]
        void ModificarPerfil(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/ModificarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/ModificarPerfilResponse")]
        System.Threading.Tasks.Task ModificarPerfilAsync(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/MostrarPerfiles", ReplyAction="http://tempuri.org/IWSPerfil/MostrarPerfilesResponse")]
        System.Data.DataTable MostrarPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/MostrarPerfiles", ReplyAction="http://tempuri.org/IWSPerfil/MostrarPerfilesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarPerfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/BuscarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/BuscarPerfilResponse")]
        System.Data.DataTable BuscarPerfil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPerfil/BuscarPerfil", ReplyAction="http://tempuri.org/IWSPerfil/BuscarPerfilResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarPerfilAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSPerfilChannel : CORE_INTERFACES.wsReferencePerfil.IWSPerfil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPerfilClient : System.ServiceModel.ClientBase<CORE_INTERFACES.wsReferencePerfil.IWSPerfil>, CORE_INTERFACES.wsReferencePerfil.IWSPerfil {
        
        public WSPerfilClient() {
        }
        
        public WSPerfilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPerfilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearPerfil(string Nombre, string Descripcion) {
            base.Channel.CrearPerfil(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task CrearPerfilAsync(string Nombre, string Descripcion) {
            return base.Channel.CrearPerfilAsync(Nombre, Descripcion);
        }
        
        public void EliminarPerfil(int id) {
            base.Channel.EliminarPerfil(id);
        }
        
        public System.Threading.Tasks.Task EliminarPerfilAsync(int id) {
            return base.Channel.EliminarPerfilAsync(id);
        }
        
        public void ModificarPerfil(int id, string Nombre, string Descripcion) {
            base.Channel.ModificarPerfil(id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task ModificarPerfilAsync(int id, string Nombre, string Descripcion) {
            return base.Channel.ModificarPerfilAsync(id, Nombre, Descripcion);
        }
        
        public System.Data.DataTable MostrarPerfiles() {
            return base.Channel.MostrarPerfiles();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarPerfilesAsync() {
            return base.Channel.MostrarPerfilesAsync();
        }
        
        public System.Data.DataTable BuscarPerfil(int id) {
            return base.Channel.BuscarPerfil(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarPerfilAsync(int id) {
            return base.Channel.BuscarPerfilAsync(id);
        }
    }
}
